//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.11.28 at 05:32:52 PM IST
//

package com.pineapplepayments.paya.connector.soap.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * com.pineapplepayments.paya.connector.soap.model package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java
 * representation of XML content can consist of schema derived interfaces and classes representing the binding of schema type
 * definitions, element declarations and model groups. Factory methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AuthGatewayHeader_QNAME = new QName("http://tempuri.org/GETI.eMagnus.WebServices/AuthGateway",
            "AuthGatewayHeader");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * com.pineapplepayments.paya.connector.soap.model
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AuthGatewayCertification }
     *
     */
    public AuthGatewayCertification createAuthGatewayCertification() {
        return new AuthGatewayCertification();
    }

    /**
     * Create an instance of {@link AuthGatewayCertificationResponse }
     *
     */
    public AuthGatewayCertificationResponse createAuthGatewayCertificationResponse() {
        return new AuthGatewayCertificationResponse();
    }

    /**
     * Create an instance of {@link AuthGatewayHeader }
     *
     */
    public AuthGatewayHeader createAuthGatewayHeader() {
        return new AuthGatewayHeader();
    }

    /**
     * Create an instance of {@link GetCertificationTerminalSettings }
     *
     */
    public GetCertificationTerminalSettings createGetCertificationTerminalSettings() {
        return new GetCertificationTerminalSettings();
    }

    /**
     * Create an instance of {@link GetCertificationTerminalSettingsResponse }
     *
     */
    public GetCertificationTerminalSettingsResponse createGetCertificationTerminalSettingsResponse() {
        return new GetCertificationTerminalSettingsResponse();
    }

    /**
     * Create an instance of {@link ProcessSingleCertificationCheck }
     *
     */
    public ProcessSingleCertificationCheck createProcessSingleCertificationCheck() {
        return new ProcessSingleCertificationCheck();
    }

    /**
     * Create an instance of {@link ProcessSingleCertificationCheckResponse }
     *
     */
    public ProcessSingleCertificationCheckResponse createProcessSingleCertificationCheckResponse() {
        return new ProcessSingleCertificationCheckResponse();
    }

    /**
     * Create an instance of {@link ProcessSingleCertificationCheckWithToken }
     *
     */
    public ProcessSingleCertificationCheckWithToken createProcessSingleCertificationCheckWithToken() {
        return new ProcessSingleCertificationCheckWithToken();
    }

    /**
     * Create an instance of {@link ProcessSingleCertificationCheckWithTokenResponse }
     *
     */
    public ProcessSingleCertificationCheckWithTokenResponse createProcessSingleCertificationCheckWithTokenResponse() {
        return new ProcessSingleCertificationCheckWithTokenResponse();
    }

    /**
     * Create an instance of {@link GetCertificationToken }
     *
     */
    public GetCertificationToken createGetCertificationToken() {
        return new GetCertificationToken();
    }

    /**
     * Create an instance of {@link GetCertificationTokenResponse }
     *
     */
    public GetCertificationTokenResponse createGetCertificationTokenResponse() {
        return new GetCertificationTokenResponse();
    }

    /**
     * Create an instance of {@link ParseCertificationMICR }
     *
     */
    public ParseCertificationMICR createParseCertificationMICR() {
        return new ParseCertificationMICR();
    }

    /**
     * Create an instance of {@link ParseCertificationMICRResponse }
     *
     */
    public ParseCertificationMICRResponse createParseCertificationMICRResponse() {
        return new ParseCertificationMICRResponse();
    }

    /**
     * Create an instance of {@link GetTerminalSettings }
     *
     */
    public GetTerminalSettings createGetTerminalSettings() {
        return new GetTerminalSettings();
    }

    /**
     * Create an instance of {@link GetTerminalSettingsResponse }
     *
     */
    public GetTerminalSettingsResponse createGetTerminalSettingsResponse() {
        return new GetTerminalSettingsResponse();
    }

    /**
     * Create an instance of {@link ProcessSingleCheck }
     *
     */
    public ProcessSingleCheck createProcessSingleCheck() {
        return new ProcessSingleCheck();
    }

    /**
     * Create an instance of {@link ProcessSingleCheckResponse }
     *
     */
    public ProcessSingleCheckResponse createProcessSingleCheckResponse() {
        return new ProcessSingleCheckResponse();
    }

    /**
     * Create an instance of {@link ProcessSingleCheckWithToken }
     *
     */
    public ProcessSingleCheckWithToken createProcessSingleCheckWithToken() {
        return new ProcessSingleCheckWithToken();
    }

    /**
     * Create an instance of {@link ProcessSingleCheckWithTokenResponse }
     *
     */
    public ProcessSingleCheckWithTokenResponse createProcessSingleCheckWithTokenResponse() {
        return new ProcessSingleCheckWithTokenResponse();
    }

    /**
     * Create an instance of {@link GetToken }
     *
     */
    public GetToken createGetToken() {
        return new GetToken();
    }

    /**
     * Create an instance of {@link GetTokenResponse }
     *
     */
    public GetTokenResponse createGetTokenResponse() {
        return new GetTokenResponse();
    }

    /**
     * Create an instance of {@link ParseMICR }
     *
     */
    public ParseMICR createParseMICR() {
        return new ParseMICR();
    }

    /**
     * Create an instance of {@link ParseMICRResponse }
     *
     */
    public ParseMICRResponse createParseMICRResponse() {
        return new ParseMICRResponse();
    }

    /**
     * Create an instance of {@link GetArchivedResponse }
     *
     */
    public GetArchivedResponse createGetArchivedResponse() {
        return new GetArchivedResponse();
    }

    /**
     * Create an instance of {@link GetArchivedResponseResponse }
     *
     */
    public GetArchivedResponseResponse createGetArchivedResponseResponse() {
        return new GetArchivedResponseResponse();
    }

    /**
     * Create an instance of {@link RemoteAccessHeader }
     *
     */
    public RemoteAccessHeader createRemoteAccessHeader() {
        return new RemoteAccessHeader();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthGatewayHeader }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://tempuri.org/GETI.eMagnus.WebServices/AuthGateway", name = "AuthGatewayHeader")
    public JAXBElement<AuthGatewayHeader> createAuthGatewayHeader(AuthGatewayHeader value) {
        return new JAXBElement<>(_AuthGatewayHeader_QNAME, AuthGatewayHeader.class, null, value);
    }

}
