//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.11.28 at 05:32:52 PM IST
//

package com.pineapplepayments.paya.connector.soap.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ParseCertificationMICRResult" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "parseCertificationMICRResult"
})
@XmlRootElement(name = "ParseCertificationMICRResponse")
public class ParseCertificationMICRResponse {

    @XmlElement(name = "ParseCertificationMICRResult")
    protected String parseCertificationMICRResult;

    /**
     * Gets the value of the parseCertificationMICRResult property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getParseCertificationMICRResult() {
        return parseCertificationMICRResult;
    }

    /**
     * Sets the value of the parseCertificationMICRResult property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setParseCertificationMICRResult(String value) {
        parseCertificationMICRResult = value;
    }

}
